"""add transactions and settlements

Revision ID: ce158f938857
Revises: 66d4577642b0
Create Date: 2026-09-23 00:29:22.284357
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce158f938857'
down_revision: Union[str, None] = '66d4577642b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', name='transaction_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', name='transaction_status', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('competence_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(status = 'ACTIVE' AND cancelled_at IS NULL AND cancellation_reason IS NULL) OR (status = 'CANCELLED' AND cancelled_at IS NOT NULL)", name=op.f('ck_transactions_cancellation_state_consistent')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transactions_amount_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name=op.f('fk_transactions_subcategory_id_subcategories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_subcategory_id'), 'transactions', ['subcategory_id'], unique=False)
    op.create_index('ix_transactions_user_competence_date', 'transactions', ['user_id', 'competence_date'], unique=False)
    op.create_index('ix_transactions_user_status_due_date', 'transactions', ['user_id', 'status', 'due_date'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_settlements_amount_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_settlements_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_settlements_transaction_id_transactions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_index(op.f('ix_settlements_account_id'), 'settlements', ['account_id'], unique=False)
    op.create_index('ix_settlements_account_settled_at', 'settlements', ['account_id', 'settled_at'], unique=False)
    op.create_index(op.f('ix_settlements_transaction_id'), 'settlements', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlements_transaction_id'), table_name='settlements')
    op.drop_index('ix_settlements_account_settled_at', table_name='settlements')
    op.drop_index(op.f('ix_settlements_account_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index('ix_transactions_user_status_due_date', table_name='transactions')
    op.drop_index('ix_transactions_user_competence_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_subcategory_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
